version: '3.8'

services:
  db:
    image: mysql:8.0
    user: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "default"
      TZ: "UTC"
    volumes:
      - ./database/sql:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost"
      timeout: 20s
      retries: 10

  migration:
    build:
      context: .
      dockerfile: images/sqldef/Dockerfile
    environment:
      MYSQL_DATABASE: default
      MYSQL_USER: root
      MYSQL_PWD: password
      MYSQL_HOST: db
      MYSQL_TCP_PORT: 3306
      SQL_FILE_TO_MIGRATE_APPLICATION_DATABASE: "/mysql/schema.sql"
    volumes:
      - ./database/sql:/mysql
    depends_on:
      db:
        condition: service_healthy
