CREATE TABLE logs (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE log_formats (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  format VARCHAR(255) NOT NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT `fk_log_formats_log_id` FOREIGN KEY (`id`) REFERENCES `logs` (`id`)
) Engine=InnoDB DEFAULT CHARSET=utf8mb4;
